spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    vault:
      scheme: http
      authentication: TOKEN
      host: 127.0.0.1
      port: 8200
      token: Yf7dP5TuAD6ygJBoVDa2Bg2U
      kv:
        enabled: true
  config:
    import: vault://
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

application:
  security:
    jwt:
      secret-key: ${jwt.secretKey}
      expiration: ${jwt.expiration} #1 ngày


      refresh-token:
        expiration: 604800000 # 7 ngày
  config:
    order-url: http://localhost:8060/api/orders

logging:
  level:
    com.huuduc.authservice.logging: INFO
  file:
    name: auth-service/access_logs/access.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env
  endpoint:
    health:
      show-details: always
    env:
      post:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8050
