spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/orders/**

        - id: product-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/products/**

        - id: product_service_swagger
          uri: http://localhost:8080
          predicates:
            - Path=/aggregate/product-service/v3/api-docs
          filters:
            - SetPath=/api-docs

        - id: order_service_swagger
          uri: http://localhost:8060
          predicates:
            - Path=/aggregate/order-service/v3/api-docs
          filters:
            - SetPath=/api-docs

        - id: auth_service_swagger
          uri: http://localhost:8050
          predicates:
            - Path=/aggregate/auth-service/v3/api-docs
          filters:
            - SetPath=/api-docs
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Gateway-Service
        url: /v3/api-docs
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs
      - name: Auth Service
        url: /aggregate/auth-service/v3/api-docs



management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoint:
      health:
        show-details: always
  endpoints:
      web:
        exposure:
          include: health,info,prometheus

resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        minimumNumberOfCalls: 5

server:
  port: 8222
